language: cpp

compiler:
  - gcc

before_script:
  - git submodule add https://github.com/google/googletest.git gtest
  - mkdir build
  - cd build
  - cmake ..

script:
  - make

after_test:
  - git submodule deinit -f -- gtest
  - rm -rf .git/modules/gtest
  - git rm -f gtest
