language: cpp

compiler:
  - gcc

addons:
  apt:
    packages: lcov

before_script:
  - git submodule add https://github.com/google/googletest.git gtest
  - mkdir build
  - cd build
  - cmake -DRUN_TESTS=ON -DCHECK_COVERAGE=ON ..

script:
  - make

after_success:
  - git submodule deinit -f -- gtest
  - rm -rf .git/modules/gtest
  - git rm -f gtest
  - lcov -a tests/grid1_coverage.info.cleaned -a tests/grid2_coverage.info.cleaned -a tests/grid3_coverage.info.cleaned -a tests/grid4_coverage.info.cleaned -a tests/grid5_coverage.info.cleaned -o total.info
  - bash <(curl -s https://codecov.io/bash) -f total.info || echo "Codecov did not collect coverage reports"
